# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_mining', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mining',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mining',
            name='likes',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
