# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_mining', '0002_auto_20170923_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='mining',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
