# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_mining', '0003_auto_20170926_0356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page_feed',
            options={'verbose_name': 'PAGE FEED', 'verbose_name_plural': 'PAGE FEED'},
        ),
        migrations.AlterField(
            model_name='page_feed',
            name='page_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
