# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 03:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_mining', '0008_auto_20170928_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitter',
            old_name='user_id',
            new_name='tweet_id',
        ),
    ]
